# Generated by Django 4.1.2 on 2022-10-09 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('seccion', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('ap_paterno', models.CharField(max_length=100)),
                ('ap_materno', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ACTIVISTA', 'ACTIVISTA'), ('ACTIVADO', 'ACTIVADO'), ('CONTRA', 'CONTRA'), ('OTROS', 'OTROS')], default='ACTIVISTA', max_length=15)),
                ('domicilio', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=10)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoyos.localidad')),
            ],
            options={
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='EncargadoRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('ap_paterno', models.CharField(max_length=100)),
                ('ap_materno', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('HOMBRE', 'HOMBRE'), ('MUJER', 'MUJER')], default='HOMBRE', max_length=10)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('domicilio', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('comunidades', models.ManyToManyField(to='apoyos.localidad')),
            ],
            options={
                'verbose_name_plural': 'Encargados de Ruta',
            },
        ),
        migrations.CreateModel(
            name='Apoyos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ECONOMICO', 'ECONOMICO'), ('VIVIENDA', 'VIVIENDA'), ('SALUD', 'SALUD'), ('COMBUSTIBLE', 'COMBUSTIBLE'), ('OTROS', 'OTROS')], default='ECONOMICO', max_length=20)),
                ('descripcion', models.TextField(max_length=250)),
                ('fecha_de_entrega', models.DateField(blank=True, null=True)),
                ('comprobacion', models.ImageField(null=True, upload_to='apoyos/')),
                ('notas_adicionales', models.TextField(blank=True, max_length=500, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoyos.persona')),
            ],
            options={
                'verbose_name_plural': 'Apoyos',
            },
        ),
    ]
