# Generated by Django 4.1.2 on 2022-10-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoyos',
            name='persona_que_entrego',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
