# Generated by Django 4.1.2 on 2022-10-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0002_apoyos_persona_que_entrego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyos',
            name='comprobacion',
            field=models.ImageField(blank=True, null=True, upload_to='apoyos/'),
        ),
        migrations.AlterField(
            model_name='encargadoruta',
            name='domicilio',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='seccion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ap_materno',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='domicilio',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
