# Generated by Django 4.1.2 on 2022-10-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0003_alter_apoyos_comprobacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargadoruta',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
