# Generated by Django 4.1.2 on 2022-10-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0004_alter_encargadoruta_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidad',
            name='numero_habitantes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
