# Generated by Django 4.1.2 on 2022-10-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0005_localidad_numero_habitantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='ap_materno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ap_paterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
