# Generated by Django 4.1.2 on 2022-10-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0006_alter_persona_ap_materno_alter_persona_ap_paterno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyos',
            name='tipo',
            field=models.CharField(choices=[('ECONOMICO', 'ECONOMICO'), ('VIVIENDA', 'VIVIENDA'), ('SALUD', 'SALUD'), ('COMBUSTIBLE', 'COMBUSTIBLE'), ('IMPLEMENTOS', 'IMPLEMENTOS'), ('SEMILLAS DE CULTIVO', 'SEMILLAS DE CULTIVO'), ('OTROS', 'OTROS')], default='ECONOMICO', max_length=20),
        ),
    ]
