# Generated by Django 4.1.2 on 2022-10-13 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0008_apoyos_encargado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apoyos',
            old_name='encargado',
            new_name='encargado_de_ruta',
        ),
        migrations.RemoveField(
            model_name='apoyos',
            name='persona_que_entrego',
        ),
    ]
