# Generated by Django 4.1.2 on 2022-10-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0009_rename_encargado_apoyos_encargado_de_ruta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_de_empleados', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='encargadoruta',
            name='departamentos',
            field=models.ManyToManyField(to='apoyos.departamento'),
        ),
    ]
