# Generated by Django 4.1.2 on 2022-10-14 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0010_departamento_encargadoruta_departamentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encargadoruta',
            name='departamentos',
        ),
    ]
