# Generated by Django 4.1.2 on 2022-10-14 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0011_remove_encargadoruta_departamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargadoruta',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apoyos.departamento'),
            preserve_default=False,
        ),
    ]
