# Generated by Django 4.1.2 on 2022-10-17 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0012_encargadoruta_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Puestos',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ap_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('ap_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('domicilio', models.TextField(blank=True, max_length=250, null=True)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], default='MASCULINO', max_length=15)),
                ('status', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=10)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoyos.departamento')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoyos.puesto')),
            ],
            options={
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
