# Generated by Django 4.1.2 on 2022-10-17 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0013_puesto_empleado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='sexo',
            new_name='genero',
        ),
    ]
