# Generated by Django 4.1.2 on 2022-10-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0014_rename_sexo_empleado_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='genero',
            field=models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], default='MASCULINO', max_length=15),
        ),
    ]
