# Generated by Django 4.1.2 on 2022-10-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0015_persona_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargadoruta',
            name='ap_materno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='encargadoruta',
            name='ap_paterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
