# Generated by Django 4.1.2 on 2022-10-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0017_empleado_sueldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidad',
            name='tipo',
            field=models.CharField(choices=[('RURAL', 'RURAL'), ('URBANO(A)', 'URBANO(A)')], default='URBANO(A)', max_length=12),
        ),
    ]
