# Generated by Django 4.1.2 on 2022-10-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0018_localidad_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='seccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='tipo',
            field=models.CharField(choices=[('RURAL', 'RURAL'), ('URBANO(A)', 'URBANO(A)')], max_length=12),
        ),
    ]
