# Generated by Django 4.1.2 on 2022-10-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0019_alter_localidad_seccion_alter_localidad_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Secciones',
            },
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='seccion',
        ),
    ]
