# Generated by Django 4.1.2 on 2022-10-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0021_delete_seccion_localidad_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargadoruta',
            name='domicilio',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='tipo',
            field=models.CharField(choices=[('RURAL', 'RURAL'), ('URBANO(A)', 'URBANO(A)')], default='RURAL', max_length=12),
        ),
    ]
