# Generated by Django 4.1.2 on 2022-10-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0022_alter_encargadoruta_domicilio_alter_localidad_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apoyos',
            old_name='comprobacion',
            new_name='foto_de_comprobacion',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='domicilio',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
