# Generated by Django 4.1.2 on 2022-10-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0023_rename_comprobacion_apoyos_foto_de_comprobacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyos',
            name='descripcion',
            field=models.CharField(max_length=250),
        ),
    ]
