# Generated by Django 4.1.2 on 2022-10-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0024_alter_apoyos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyos',
            name='notas_adicionales',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
