# Generated by Django 4.1.2 on 2022-10-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0028_alter_empleado_tipo_de_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo_de_empleado',
            field=models.CharField(choices=[('SINDICALIZADO', 'SINDICALIZADO'), ('EVENTUAL', 'EVENTUAL'), ('CONTRATO', 'CONTRATO'), ('OTROS', 'OTROS')], default='SINDICALIZADO', max_length=20),
        ),
    ]
