# Generated by Django 4.1.2 on 2022-10-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0029_persona_curp_alter_empleado_tipo_de_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='titular',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
