# Generated by Django 4.1.2 on 2022-10-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0030_departamento_titular'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
