# Generated by Django 4.1.2 on 2022-11-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0031_departamento_email_departamento_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
