# Generated by Django 4.1.3 on 2022-12-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyos', '0036_alter_puesto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
