# Generated by Django 4.1.3 on 2022-11-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ap_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('ap_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], default='MASCULINO', max_length=15)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('expediente', models.ImageField(blank=True, null=True, upload_to='espedientes/')),
                ('notas_adicionales', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contribuyentes',
            },
        ),
    ]
