# Generated by Django 4.1.3 on 2022-11-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuyente',
            name='expediente',
            field=models.FileField(blank=True, null=True, upload_to='expedientes/'),
        ),
    ]
