# Generated by Django 4.1.3 on 2022-12-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0002_alter_contribuyente_expediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuyente',
            name='domicilio',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
