# Generated by Django 4.1.3 on 2022-12-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0003_contribuyente_domicilio_contribuyente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuyente',
            name='numero_de_cuenta_predial',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
